# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Cache resume pdf
        id: cache-resume-pdf
        uses: actions/cache@v2
        env:
          cache-name: cache-resume-pdf
        with:
          path: example/static/resume.pdf
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/example/static/resume.tex') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build resume pdf
        if: steps.cache-resume-pdf.outputs.cache-hit != 'true'
        uses: xu-cheng/latex-action@v2
        with:
          root_file: example/static/resume.tex
          post_compile: "rm example/static/resume.tex && cp resume.pdf example/static/resume.pdf"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: yarn
      - run: yarn workspace example build
      - name: Deploy to GitHub Pages
        if: success() && github.ref == 'refs/heads/master'
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: example/public
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
